project:
  type: website
  output-dir: docs

website:
  title: "Statistics Bee"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Pages/about.qmd
        text: About
      - href: Pages/apply.qmd
        text: Apply

  page-footer: "Site Designed by Ethan Marzban using Quarto; ©2023"
  favicon: "Images/Logos_Icons/favicon.png"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
